server:
  port: 8080

spring:
  profiles:
    default: local
  application:
    name: issueflow
  config:
    import: optional:classpath:application-local.yaml
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
